//! Conformance: each `tests/fixtures/<name>.json` (a `{version, submissions}`
//! input, or `{versions, submissions}` for a multi-version merge) must export
//! to a CSV byte-identical to its golden `tests/fixtures/<name>.csv` — the
//! output of the reference exporter. A `.tables` golden instead selects the
//! multi-section export.
//!
//! Goldens are generated by the reference implementation and committed; this
//! test needs no external tooling.

use std::fs;
use std::path::Path;

use serde_json::Value;

#[test]
fn csv_fixtures_match_reference() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let mut checked = 0;

    for entry in fs::read_dir(&dir).expect("fixtures directory") {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        // `<name>.xlsx.json` / `<name>.report.json` goldens belong to the XLSX
        // and report conformance tests.
        let name = path.to_string_lossy();
        if name.ends_with(".xlsx.json") || name.ends_with(".report.json") {
            continue;
        }
        // A fixture whose golden is `<name>.geojson` or `<name>.report.json`
        // belongs to another conformance test, not this CSV one.
        if path.with_extension("geojson").exists() || path.with_extension("report.json").exists() {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("fixture stem")
            .to_owned();

        let input: Value =
            serde_json::from_str(&fs::read_to_string(&path).expect("read fixture json"))
                .expect("parse fixture json");
        let submissions: Vec<Value> = input["submissions"]
            .as_array()
            .expect("submissions array")
            .clone();
        let lang = input.get("lang").and_then(Value::as_str);
        let mode = input
            .get("multiple_select")
            .and_then(Value::as_str)
            .unwrap_or("both");
        let copy_owned: Vec<String> = input
            .get("copy_fields")
            .and_then(Value::as_array)
            .map(|items| {
                items
                    .iter()
                    .filter_map(Value::as_str)
                    .map(str::to_owned)
                    .collect()
            })
            .unwrap_or_default();
        let copy_fields: Vec<&str> = copy_owned.iter().map(String::as_str).collect();

        let tables_path = dir.join(format!("{stem}.tables"));
        let (got, golden_path) = if let Some(versions) =
            input.get("versions").and_then(Value::as_array)
        {
            // `versions` (plural) → multi-version merge, CSV only.
            (
                tableflow::export_csv_versions(versions, &submissions, lang, mode),
                dir.join(format!("{stem}.csv")),
            )
        } else if tables_path.exists() {
            // A `.tables` golden selects the multi-section export.
            let title = input
                .get("title")
                .and_then(Value::as_str)
                .unwrap_or("submissions");
            (
                tableflow::export_tables_text(
                    &input["version"],
                    &submissions,
                    lang,
                    title,
                    mode,
                    &copy_fields,
                ),
                tables_path,
            )
        } else {
            (
                tableflow::export_csv(&input["version"], &submissions, lang, mode, &copy_fields),
                dir.join(format!("{stem}.csv")),
            )
        };

        let golden = fs::read_to_string(&golden_path)
            .unwrap_or_else(|_| panic!("missing golden for `{stem}`"));
        let golden = golden.strip_suffix('\n').unwrap_or(&golden);

        assert_eq!(got, golden, "export mismatch for fixture `{stem}`");
        checked += 1;
    }

    assert!(checked >= 1, "no fixtures found");
}
